[connections.supabase]
SUPABASE_URL = "https://vnhstgzurrpktwoavsrq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaHN0Z3p1cnJwa3R3b2F2c3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDIyNzQ5NTksImV4cCI6MjAxNzg1MDk1OX0.tnVEfSXiqERs9gVvScp5o2b8ToOrtiZy2v7Jn-mewgU"
